apiVersion: v1
kind: Service
metadata:
  namespace: nodoo
  name: postgresip # Sets service name
  labels:
    app: postgres # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - port: 5432 # Sets port to run the postgres application
      targetPort: 5432
  selector:
    app: postgres